name: Haxel Build
on:
  push:
  # add other event triggers
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - run: | 
          haxe -version
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install flixel-tools
          haxelib install hscript
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run flixel-tools setup
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons

